name: BuildAndTestOnEveryPush

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        AWS.SQS.aws_access_key_id: ${{ secrets.AWS_SQS_aws_access_key_id }}
        AWS.SQS.aws_secret_access_key: ${{ secrets.AWS_SQS_aws_secret_access_key }}
        AWS.SQS.aws_sqs_queue: ${{ secrets.AWS_SQS_aws_sqs_queue }}
        AWS.SQS.aws_sqs_region: ${{ secrets.AWS_SQS_aws_sqs_region }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.AWS.SQS\bin\Release\Frends.Community.AWS.SQS.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package --symbol-source https://www.myget.org/F/frends-community-test/symbols/api/v2/package